In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/freez-ai/train.csv
/kaggle/input/freez-ai/freezai/sample_submission.csv
/kaggle/input/freez-ai/freezai/train.csv
/kaggle/input/freez-ai/freezai/test.csv

In [2]:
df = pd.read_csv("/kaggle/input/freez-ai/freezai/train.csv")

In [3]:
df.head()

,id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,267,0,138,0,0,0,36.3,0.933,25,1
1,627,0,125,68,0,0,24.7,0.206,21,0
2,84,0,101,65,28,0,24.6,0.237,22,0
3,62,8,133,72,0,0,32.9,0.270,39,1
4,633,2,111,60,0,0,26.2,0.343,23,0

In [4]:
test=pd.read_csv("/kaggle/input/freez-ai/freezai/test.csv")

In [5]:
test.head()

,id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,669,6,98,58,33,190,34.0,0.430,43
1,325,2,112,75,32,0,35.7,0.148,21
2,625,2,108,64,0,0,30.8,0.158,21
3,691,8,107,80,0,0,24.6,0.856,34
4,474,7,136,90,0,0,29.9,0.210,50

In [6]:
       X=df.drop(["id", "Outcome"] , axis=1)

In [7]:
y=df["Outcome"]

In [8]:
X_test= test.drop(["id"] , axis=1)

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [10]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
rf_model = RandomForestClassifier(n_estimators=25, random_state=42)  # You can adjust n_estimators (number of trees)

In [12]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=25, random_state=42)

In [13]:
X_test.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,98,58,33,190,34.0,0.430,43
1,2,112,75,32,0,35.7,0.148,21
2,2,108,64,0,0,30.8,0.158,21
3,8,107,80,0,0,24.6,0.856,34
4,7,136,90,0,0,29.9,0.210,50

In [14]:
y_pred = rf_model.predict(X_val)
pred = rf_model.predict(X_test)

In [15]:
accuracy = accuracy_score(y_val, y_pred)
print(f"Validation Accuracy: {accuracy:.4f}")

Validation Accuracy: 0.7642

In [16]:
test.head()

,id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,669,6,98,58,33,190,34.0,0.430,43
1,325,2,112,75,32,0,35.7,0.148,21
2,625,2,108,64,0,0,30.8,0.158,21
3,691,8,107,80,0,0,24.6,0.856,34
4,474,7,136,90,0,0,29.9,0.210,50

In [17]:
submission = pd.DataFrame({
    'id': test[ 'id'],
    'Outcome': pred
})
submission.head()

    id  Outcome
0  669        1
1  325        0
2  625        0
3  691        0
4  474        0

In [18]:
submission.to_csv('submission.csv', index=False)